package com.example.yumarketforowners.core.util

import kotlinx.coroutines.CancellationException

inline fun <R> runCoroutineCatching(block: () -> R): Result<R> {
    return try {
        Result.success(block())
    } catch (cancellationException: CancellationException) {
        throw cancellationException
    } catch (e: Throwable) {
        Result.failure(e)
    }
}

inline fun <T, R> T.runCoroutineCatching(block: T.() -> R): Result<R> {
    return try {
        Result.success(block())
    } catch (cancellationException: CancellationException) {
        throw cancellationException
    } catch (e: Throwable) {
        Result.failure(e)
    }
}